name: Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            asset_name: metire-linux-x86_64
            compile_output: metire
          - os: windows-latest
            asset_name: metire-windows-x86_64.exe
            compile_output: metire.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart compile exe bin/metire.dart -o ${{ matrix.compile_output }}
      - run: mkdir release && mv ${{ matrix.compile_output }} release/${{ matrix.asset_name }}
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: release/${{ matrix.asset_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: release
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          files: release/*
          body: |
            **Metire ${{ github.ref_name }}**

            - Linux x86_64 binary
            - Windows x86_64 binary
